package com.paximum.paxassist.validator;

import com.paximum.paxassist.validator.config.ValidatorProperties;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.metadata.Usage;
import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.ai.chat.prompt.ChatOptions;
import org.springframework.ai.converter.BeanOutputConverter;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.lang.NonNull;
import org.springframework.stereotype.Service;

import java.net.ConnectException;
import java.time.LocalDate;
import java.util.regex.Pattern;

/**
 * Calls the Validator's dedicated local {@code ChatClient} (see {@code ValidatorConfig}) to judge a
 * candidate answer from the main LLM. Kept fully independent of the {@code chat}/{@code ai} packages —
 * it has its own retry/error-classification logic rather than reusing {@code ChatService}'s, so this
 * module never compiles against forbidden-package internals.
 */
@Service
public class ValidatorService {

    private static final Logger log = LoggerFactory.getLogger(ValidatorService.class);

    private static final int MAX_TRANSIENT_ATTEMPTS = 3;
    private static final long BASE_DELAY_MS = 200;

    /** Everything up to (and including) the last {@code </think>} close tag, any case/spacing. */
    private static final Pattern REASONING_BLOCK = Pattern.compile("(?is)^.*</\\s*think\\s*>");

    private static final String VALIDATION_SYSTEM_PROMPT = """
            ── ROLE & CORE FUNCTION ──────────────────────────────────────────────
            You are a strict, second-layer Validation Module (Critic/Validator) that
            reviews the Candidate Response generated by a travel assistant (Main LLM).
            You are NOT a conversation participant. You act as a strict referee evaluating
            the candidate as either APPROVED or REJECTED.

            Your REJECTED verdict and feedback will be routed back to the Main LLM as a
            self-correction prompt, forcing it to RE-GENERATE its response. Therefore, your
            feedback must be precise, actionable, and clear enough for the Main LLM to fix its mistake.

            ── IMPORTANT: NORMAL ASSISTANT BEHAVIOR (DO NOT REJECT) ───────────────
            The assistant is NOT required to return search results or JSON in every turn.
            The following are normal, safe behaviors. DO NOT REJECT for these reasons:
              - Asking a single follow-up question to complete missing parameters (e.g., dates, passenger counts).
              - Asking to clarify whether the user wants a hotel or a flight — EXCEPTION: If the
                product type is already explicit in the user's prompt, asking "hotel or flight?"
                is an assistant error; REJECT it. Explicit means hotel words like "hotel", "room",
                "stay" (Turkish: "otel", "oda", "konaklama") OR flight words like "flight", "fly"
                (Turkish: "uçuş", "uçmak", "bilet") or an obvious flight itinerary (origin-destination
                route, cabin class, one-way/round-trip).
              - Politeness/Refusals regarding out-of-scope, operational, policy, or budget issues
                (e.g., cancellation policies, pet rules, extreme requests like "4 cows", or "10 TL budget")
                as long as it doesn't hallucinate data.
              - Handling heavy typos (e.g., "iştanbuılafn sanalyaya") or vague pronouns ("this", "there")
                by asking for clarification.
              - Introducing itself (its name, purpose, or the company that built it) when the user asks
                who or what it is.

            ── INPUTS ────────────────────────────────────────────────────────────
            USER_PROMPT: The user's original message (usually in Turkish).
            CANDIDATE_RESPONSE: The output generated by the Main LLM (Text or JSON).
            CONTEXT: The factual data ground truth (search results, system data). Can be empty.
            TODAY_DATE: Reference date for checking timeline logic.

            ── EVALUATION CRITERIA ───────────────────────────────────────────────
            1. Date & Timeline Logic: Travel/booking dates in CANDIDATE_RESPONSE cannot be in the
               past relative to TODAY_DATE. Even if the user asks for a past date, the assistant
               must refuse. If the assistant accepts or incorrectly maps relative dates (e.g., "this Friday")
               to a past/wrong date, REJECT.
            2. Hallucination (Fabricated Data): Does CANDIDATE_RESPONSE contain any price, availability,
               hotel/flight name, flight duration, connection info, or amenities (pool, aqua park, etc.)
               NOT present in the CONTEXT? If yes, REJECT.
               - Exception: If CONTEXT is empty and the user asks for filtered recommendations (e.g., "no kids",
                 "separate pools"), the assistant fabricating specific property names is an immediate REJECT.
               - Fabricating "top 10 worst reviews" or sightseeing info outside of CONTEXT is a REJECT.
               - Confirming a user's selection ("I want the first hotel", "select flight 2") by presenting a
                 specific product summary (name, price, availability) when CONTEXT contains no such list is
                 fabricated data; REJECT.
               - Fabricating a prior-conversation memory, or casually mentioning a specific destination,
                 city, or date the user never stated (e.g., "as I recall you were looking for a hotel in
                 Antalya" when the user never mentioned Antalya), is also fabricated data; REJECT.
            3. Scope, Safety & Logic Boundaries:
               - If the user tries to exploit logic (e.g., "applying child discount for a single adult" or
                 "registering cows as child passengers") and the assistant accepts it into the system data, REJECT.
               - If the user requests cancellations/refunds and the assistant unauthorizedly promises
                 "Cancelled" or "Refunded" without system authority, REJECT.
               - Out-of-scope fulfillment: If the user's request is outside hotel/flight search scope
                 (jokes, general knowledge, weather, news, etc.) and the assistant FULFILLS it instead of
                 politely declining and redirecting to travel search, REJECT. (Politely declining such
                 requests is normal behavior — see above.)
            4. Empty Context Rule: If CONTEXT is empty, only evaluate criteria 1, 2, and 3. Do not assume
               or fabricate what the truth "should be". Do not reject simply because the response is incomplete
               or yields no results.
            5. When in doubt, lean towards REJECTED (only for genuine ambiguities regarding criteria 1-3).

            ── OUTPUT FORMAT ─────────────────────────────────────────────────────
            Return ONLY a JSON object. Do not include markdown formatting, code blocks, or any text outside the JSON.

            {
              "verdict": "APPROVED" or "REJECTED",
              "feedback": "If APPROVED, a brief confirmation note. If REJECTED, provide a 1-2 sentence precise, actionable instruction in ENGLISH explaining which criterion (1-3) was violated and exactly how the Main LLM should correct its response."
            }
            """;

    private final ChatClient validatorChatClient;
    private final ValidatorProperties validatorProperties;
    private final BeanOutputConverter<ValidationResult> outputConverter =
            new BeanOutputConverter<>(ValidationResult.class);

    public ValidatorService(@Qualifier("validatorChatClient") ChatClient validatorChatClient,
                             ValidatorProperties validatorProperties) {
        this.validatorChatClient = validatorChatClient;
        this.validatorProperties = validatorProperties;
    }

    public ValidatorCallResult validate(@NonNull String question, @NonNull String candidateAnswer,
                                         String groundingContext) {
        ValidatorException lastError = null;
        for (int attempt = 1; attempt <= MAX_TRANSIENT_ATTEMPTS; attempt++) {
            long startNanos = System.nanoTime();
            try {
                ChatResponse chatResponse = validatorChatClient.prompt()
                        .system(VALIDATION_SYSTEM_PROMPT)
                        .user(buildUserPrompt(question, candidateAnswer, groundingContext))
                        .options(ChatOptions.builder()
                                .temperature(validatorProperties.temperature())
                                .maxTokens(validatorProperties.maxTokens())
                                .build())
                        .call()
                        .chatResponse();

                long latencyMs = elapsedMs(startNanos);

                if (chatResponse == null || chatResponse.getResult() == null
                        || chatResponse.getResult().getOutput() == null) {
                    throw new ValidatorException(ValidatorException.Code.UNKNOWN, "Validator yanıt üretemedi");
                }

                ValidatorMetrics metrics = extractMetrics(latencyMs, chatResponse);
                String content = chatResponse.getResult().getOutput().getText();
                return new ValidatorCallResult(parseOrFailClosed(content, metrics), metrics);
            } catch (ValidatorException e) {
                if (isRetryable(e) && attempt < MAX_TRANSIENT_ATTEMPTS) {
                    lastError = e;
                    log.warn("validator.call attempt={} latencyMs={} retrying code={}", attempt,
                            elapsedMs(startNanos), e.getCode());
                    sleep(BASE_DELAY_MS * attempt);
                } else {
                    throw e;
                }
            } catch (RuntimeException e) {
                ValidatorException classified = classify(e);
                if (isRetryable(classified) && attempt < MAX_TRANSIENT_ATTEMPTS) {
                    lastError = classified;
                    log.warn("validator.call attempt={} latencyMs={} retrying code={}", attempt,
                            elapsedMs(startNanos), classified.getCode());
                    sleep(BASE_DELAY_MS * attempt);
                } else {
                    throw classified;
                }
            }
        }
        throw (lastError != null) ? lastError
                : new ValidatorException(ValidatorException.Code.UNKNOWN, "Validator servisinden yanıt alınamadı");
    }

    /** Fail-closed: a verdict Spring AI can't parse is treated as REJECTED, never silently waved through. */
    private ValidationResult parseOrFailClosed(String content, ValidatorMetrics metrics) {
        ValidationResult result;
        try {
            result = outputConverter.convert(stripReasoningBlock(content));
        } catch (RuntimeException parseFailure) {
            log.warn("validator.parseFailure latencyMs={} contentLength={}", metrics.latencyMs(),
                    content == null ? 0 : content.length(), parseFailure);
            return failClosedResult();
        }
        if (result == null) {
            return failClosedResult();
        }
        log.info("validator.call latencyMs={} verdict={} promptTokens={} completionTokens={} totalTokens={}",
                metrics.latencyMs(), result.verdict(), metrics.promptTokens(), metrics.completionTokens(),
                metrics.totalTokens());
        return result;
    }

    /**
     * Deliberately does NOT append {@code outputConverter.getFormat()}: the system prompt's
     * OUTPUT FORMAT section already pins the exact JSON schema (field names match
     * {@link ValidationResult}), and the converter's auto-generated English boilerplate can
     * override the stricter hand-written rules (e.g. feedback language/content). The converter
     * is still used for parsing the response.
     */
    private String buildUserPrompt(String question, String candidateAnswer, String groundingContext) {
        String context = (groundingContext == null || groundingContext.isBlank()) ? "(empty)" : groundingContext;
        return "TODAY_DATE: " + LocalDate.now() + "\n\n"
                + "USER_PROMPT:\n" + question + "\n\n"
                + "CANDIDATE_RESPONSE:\n" + candidateAnswer + "\n\n"
                + "CONTEXT:\n" + context;
    }

    /**
     * Reasoning models (Qwen3, DeepSeek-R1 family) emit a {@code <think>…</think>} block before the
     * actual answer; drop it (and anything before its close tag) so only the JSON verdict is parsed.
     * Case-insensitive and whitespace-tolerant ({@code </THINK>}, {@code </ think >}) since providers
     * vary. Plain models are unaffected — without the tag the content passes through unchanged.
     */
    private String stripReasoningBlock(String content) {
        if (content == null) {
            return null;
        }
        return REASONING_BLOCK.matcher(content).replaceFirst("").strip();
    }

    private ValidationResult failClosedResult() {
        return new ValidationResult(ValidationResult.Verdict.REJECTED,
                "Validator output could not be parsed; rejected as a fail-closed safety measure. "
                        + "Regenerate the response strictly following the system rules.");
    }

    private ValidatorMetrics extractMetrics(long latencyMs, ChatResponse chatResponse) {
        Usage usage = chatResponse.getMetadata() == null ? null : chatResponse.getMetadata().getUsage();
        if (usage == null) {
            return new ValidatorMetrics(latencyMs, 0, 0, 0);
        }
        int promptTokens = usage.getPromptTokens() == null ? 0 : usage.getPromptTokens();
        int completionTokens = usage.getCompletionTokens() == null ? 0 : usage.getCompletionTokens();
        Integer total = usage.getTotalTokens();
        int totalTokens = total == null ? promptTokens + completionTokens : total;
        return new ValidatorMetrics(latencyMs, promptTokens, completionTokens, totalTokens);
    }

    private long elapsedMs(long startNanos) {
        return (System.nanoTime() - startNanos) / 1_000_000;
    }

    private boolean isRetryable(ValidatorException e) {
        return e.getCode() == ValidatorException.Code.UNAVAILABLE
                || e.getCode() == ValidatorException.Code.TIMEOUT
                || e.getCode() == ValidatorException.Code.RATE_LIMITED;
    }

    private void sleep(long ms) {
        try {
            Thread.sleep(ms);
        } catch (InterruptedException ie) {
            Thread.currentThread().interrupt();
        }
    }

    private ValidatorException classify(RuntimeException e) {
        String msg = fullMessage(e);
        if (msg.contains("429") || msg.contains("rate limit") || msg.contains("too many requests")) {
            return new ValidatorException(ValidatorException.Code.RATE_LIMITED, "Validator isteği limiti aşıldı", e);
        }
        if (msg.contains("timeout") || msg.contains("timed out") || msg.contains("read timed out")) {
            return new ValidatorException(ValidatorException.Code.TIMEOUT, "Validator yanıt vermedi", e);
        }
        if (msg.contains("connect") || msg.contains("refused") || msg.contains("unreachable")
                || hasCause(e, ConnectException.class)) {
            return new ValidatorException(ValidatorException.Code.UNAVAILABLE, "Validator servisine ulaşılamıyor", e);
        }
        if (msg.contains("500") || msg.contains("502") || msg.contains("503") || msg.contains("server error")) {
            return new ValidatorException(ValidatorException.Code.UNAVAILABLE,
                    "Validator sunucusu geçici hata döndürdü", e);
        }
        return new ValidatorException(ValidatorException.Code.UNKNOWN, "Validator servisinden beklenmeyen hata", e);
    }

    private String fullMessage(Throwable e) {
        StringBuilder sb = new StringBuilder();
        Throwable t = e;
        while (t != null) {
            if (t.getMessage() != null) {
                sb.append(t.getMessage().toLowerCase()).append(' ');
            }
            t = t.getCause();
        }
        return sb.toString();
    }

    private boolean hasCause(Throwable e, Class<?> type) {
        Throwable t = e.getCause();
        while (t != null) {
            if (type.isInstance(t)) {
                return true;
            }
            t = t.getCause();
        }
        return false;
    }
}
