package com.paximum.paxassist.orchestrator.intent;

import org.springframework.stereotype.Component;

import com.paximum.paxassist.ai.IntentType;
import com.paximum.paxassist.auth.service.GreetingNameService;
import com.paximum.paxassist.orchestrator.OrchestrationContext;
import com.paximum.paxassist.orchestrator.OrchestrationResult;

/**
 * Answers a bare greeting with a fixed sentence — the only reply in the chat that is guaranteed
 * word-for-word, because it is written here rather than generated by the model. A logged-in user is
 * greeted by name; a guest gets the same sentence without one.
 *
 * <p>Only messages the {@link com.paximum.paxassist.ai.GreetingDetector} recognises as <em>nothing
 * but</em> a greeting reach this handler, so "merhaba, uçak arıyorum" is still routed to the flight
 * search rather than greeted. No model call and no validator pass is involved: the text is a constant,
 * so there is nothing to ground, fabricate or validate.
 */
@Component
public class GreetingHandler implements IntentHandler {

    static final String GREETING =
            "Merhaba! Ben seyahat asistanın Paxi. Sana nasıl yardımcı olabilirim? "
                    + "Otel mi yoksa uçuş mu arıyorsun?";

    static final String NAMED_GREETING =
            "Merhaba %s! Ben seyahat asistanın Paxi. Sana nasıl yardımcı olabilirim? "
                    + "Otel mi yoksa uçuş mu arıyorsun?";

    private final GreetingNameService greetingNameService;

    public GreetingHandler(GreetingNameService greetingNameService) {
        this.greetingNameService = greetingNameService;
    }

    @Override
    public boolean supports(IntentType intent) {
        return intent == IntentType.GREETING;
    }

    @Override
    public OrchestrationResult handle(OrchestrationContext context) {
        return OrchestrationResult.message(
                greetingNameService.firstNameOf(context.session().getUserId())
                        .map(NAMED_GREETING::formatted)
                        .orElse(GREETING));
    }
}
