package com.paximum.paxassist.reservation.service;

import java.time.LocalDate;

import org.springframework.stereotype.Component;

import com.paximum.paxassist.reservation.domain.FlightReservationDetails;
import com.paximum.paxassist.reservation.domain.HotelReservationDetails;
import com.paximum.paxassist.reservation.domain.Passenger;
import com.paximum.paxassist.reservation.domain.Reservation;
import com.paximum.paxassist.reservation.domain.ReservationStatus;
import com.paximum.paxassist.reservation.service.command.PreviewReservationCommand;

/**
 * Builds ticket 1's persistence aggregate from the frozen snapshot plus TourVisio's commit result.
 * Pure mapping — the caller saves it via the repository.
 */
@Component
public class ReservationEntityMapper {

    /**
     * @param command                 the frozen snapshot that was purchased
     * @param reservationNumber       our own internal/UI code (generated by the service)
     * @param externalReservationNumber TourVisio's booking reference from CommitTransaction
     */
    public Reservation toReservation(PreviewReservationCommand command, String reservationNumber, String externalReservationNumber) {
        Reservation reservation = new Reservation();
        reservation.setReservationNumber(reservationNumber);
        reservation.setExternalReservationNumber(externalReservationNumber);
        reservation.setUserId(command.userId());
        // Guest bookings carry no user id; the opaque visitor key is the owner instead (V7).
        reservation.setGuestToken(command.guestToken());
        reservation.setStatus(ReservationStatus.CONFIRMED);
        reservation.setReservationDate(LocalDate.now());
        reservation.setTotalAmount(command.totalAmount());
        reservation.setCurrency(command.currency());
        reservation.setLeadGuestName(command.leadGuestName());

        if (command.travellers() != null) {
            for (PreviewReservationCommand.Traveller t : command.travellers()) {
                Passenger passenger = toPassenger(t);
                passenger.setReservation(reservation);
                reservation.getPassengers().add(passenger);
            }
        }

        if (command.hotel() != null) {
            HotelReservationDetails hotel = toHotelDetails(command.hotel());
            hotel.setReservation(reservation);
            reservation.setHotelDetails(hotel);
        }
        if (command.flight() != null) {
            FlightReservationDetails flight = toFlightDetails(command.flight());
            flight.setReservation(reservation);
            reservation.setFlightDetails(flight);
        }

        // Derive product type from the attached details rather than trusting input (ticket 1 rule).
        reservation.setProductType(reservation.deriveProductType());
        return reservation;
    }

    private Passenger toPassenger(PreviewReservationCommand.Traveller t) {
        Passenger p = new Passenger();
        p.setFirstName(t.firstName());
        p.setLastName(t.lastName());
        p.setPassengerType(t.passengerType());
        p.setAge(t.age());
        p.setNationality(t.nationalityCode());
        p.setEmail(t.email());
        p.setPhone(t.phone());
        return p;
    }

    private HotelReservationDetails toHotelDetails(PreviewReservationCommand.Hotel h) {
        HotelReservationDetails d = new HotelReservationDetails();
        d.setHotelName(h.hotelName());
        d.setRegion(h.region());
        d.setStars(h.stars());
        d.setBoardType(h.boardType());
        d.setCheckIn(h.checkIn());
        d.setCheckOut(h.checkOut());
        d.setRooms(h.rooms());
        d.setAdults(h.adults());
        d.setChildren(h.children());
        d.setNationality(h.nationality());
        d.setPrice(h.price());
        d.setCurrency(h.currency());
        return d;
    }

    private FlightReservationDetails toFlightDetails(PreviewReservationCommand.Flight f) {
        FlightReservationDetails d = new FlightReservationDetails();
        d.setOrigin(f.origin());
        d.setDestination(f.destination());
        d.setAirline(f.airline());
        d.setTripType(f.tripType());
        d.setDepartTime(f.departTime());
        d.setArriveTime(f.arriveTime());
        d.setReturnDepartTime(f.returnDepartTime());
        d.setReturnArriveTime(f.returnArriveTime());
        d.setStops(f.stops());
        d.setBaggage(f.baggage());
        d.setPassengerCount(f.passengerCount());
        d.setPrice(f.price());
        d.setCurrency(f.currency());
        return d;
    }
}
